//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_Fair_Split.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XamlText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XamlText() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expense_Fair_Split.Localization.XamlText", typeof(XamlText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   勘定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求データ入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BillingDataInput {
            get {
                return ResourceManager.GetString("BillingDataInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求データ照会 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BillingDataInquiry {
            get {
                return ResourceManager.GetString("BillingDataInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この名前はアプリ上で使われます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CautionText1 {
            get {
                return ResourceManager.GetString("CautionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailAddress {
            get {
                return ResourceManager.GetString("MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行う処理をタップしてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenuText {
            get {
                return ResourceManager.GetString("MainMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスタ編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterEdit {
            get {
                return ResourceManager.GetString("MasterEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスタを追加する項目を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterRegisterText {
            get {
                return ResourceManager.GetString("MasterRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingPage {
            get {
                return ResourceManager.GetString("SettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
