//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_Fair_Split.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expense_Fair_Split.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   勘定削除項目の更新中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountDelFlgUpdateFailed {
            get {
                return ResourceManager.GetString("AccountDelFlgUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   計算処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BillingCalculationErr {
            get {
                return ResourceManager.GetString("BillingCalculationErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CANCEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録を取り消しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelRegistration {
            get {
                return ResourceManager.GetString("CancelRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勘定名を空白にすることはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanNotAccNameEmpty {
            get {
                return ResourceManager.GetString("CanNotAccNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用できない文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CharacterNotAvailable {
            get {
                return ResourceManager.GetString("CharacterNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスタが登録されているか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckTheMaster {
            get {
                return ResourceManager.GetString("CheckTheMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録処理に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataInsertFailed {
            get {
                return ResourceManager.GetString("DataInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスにカメラがサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceNotSupportOnCamera {
            get {
                return ResourceManager.GetString("DeviceNotSupportOnCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレスとしての要件を満たしていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmailAddressNotRequirements {
            get {
                return ResourceManager.GetString("EmailAddressNotRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理実行中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDuringProcessing {
            get {
                return ResourceManager.GetString("ErrorDuringProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hai {
            get {
                return ResourceManager.GetString("Hai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Iie {
            get {
                return ResourceManager.GetString("Iie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像認識処理に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageRecognitionProcFailed {
            get {
                return ResourceManager.GetString("ImageRecognitionProcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択項目に不適切なものがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IncorrectSelectionItem {
            get {
                return ResourceManager.GetString("IncorrectSelectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中です。処理が終わるまで実行できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string isProcessing {
            get {
                return ResourceManager.GetString("isProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力されていない項目があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemsEmpty {
            get {
                return ResourceManager.GetString("ItemsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotEqualPassword {
            get {
                return ResourceManager.GetString("NotEqualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ViewModelが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotViewModelExists {
            get {
                return ResourceManager.GetString("NotViewModelExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム管理者にお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseContactToAdmin {
            get {
                return ResourceManager.GetString("PleaseContactToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中に問題が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProblemsInProccessing {
            get {
                return ResourceManager.GetString("ProblemsInProccessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グリッドビューの更新処理中に問題が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RefreshGridViewFailed {
            get {
                return ResourceManager.GetString("RefreshGridViewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiredItem {
            get {
                return ResourceManager.GetString("RequiredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーとの通信中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerCommunicationError {
            get {
                return ResourceManager.GetString("ServerCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動同期実行中です。時間を置いて再度実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncAutorunInProgressMsg {
            get {
                return ResourceManager.GetString("SyncAutorunInProgressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IsSynced に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncColumnStr {
            get {
                return ResourceManager.GetString("SyncColumnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローカルからサーバーへのデータ同期処理中に問題が発生したため同期処理を中断しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncFailedLocalToServer {
            get {
                return ResourceManager.GetString("SyncFailedLocalToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーからローカルへのデータ同期処理中に問題が発生したため同期処理を中断しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncFailedServerToLocal {
            get {
                return ResourceManager.GetString("SyncFailedServerToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同期処理が完了しました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyncSuccess {
            get {
                return ResourceManager.GetString("SyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム管理者に問い合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SystemAlert {
            get {
                return ResourceManager.GetString("SystemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像に対象文字が存在しませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaegetCharacterNotExistsOnImage {
            get {
                return ResourceManager.GetString("TaegetCharacterNotExistsOnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0や負の数は入力出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TargetNumZeroOrNegative {
            get {
                return ResourceManager.GetString("TargetNumZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力必須項目に空文字が入力されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TargetStringEmpty {
            get {
                return ResourceManager.GetString("TargetStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextCountExceeds {
            get {
                return ResourceManager.GetString("TextCountExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に登録されている勘定です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TheAccountIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("TheAccountIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新処理に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既にアカウント登録済みのメールアドレスです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UsedRegistrationEmailAddress {
            get {
                return ResourceManager.GetString("UsedRegistrationEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このメールアドレスによる登録はありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserNotExsistsbyEmailAddess {
            get {
                return ResourceManager.GetString("UserNotExsistsbyEmailAddess", resourceCulture);
            }
        }
    }
}
